development:
  adapter: mysql2
  encoding: utf8
  database: caffeine_monster
  pool: 5
  username: root
  password: root
  host: db
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
  database: caffeine_monster_test
  pool: 5
  username: root
  password: root
  host: db
  port: 3306
